### ISSUE TITLE
rpmlint warning: non-executable-script /usr/lib64/pluma/plugins/synctex/atril_dbus.py

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/pluma-plugins#26]
#### Expected behaviour
no warning

#### Actual behaviour
Warning when running rpmlint tool.
Note this a tool to improve RPMs

#### Steps to reproduce the behaviour
rum rpmlint tool on package

#### MATE general version
1.26

#### Package version
pluma-plugins-1.26.0

#### Linux Distribution
Fedora

#### Link to bugreport of your Distribution (requirement)
Currently i am preparing  a package review request to bring it in fedora distribution. So non distro bugreport

See info page about this warning.
http://wiki.rosalab.ru/en/index.php/Rpmlint_Errors#non-executable-script

@mbkma 
Seems this script needs an executable bit, or not?
Well, i can add this during RPM package building, but isn't it better to add this bit here?

**Comment by mbkma** [comment]
I think it already has an executable bit. Maybe you can try to remove the shebang or change the shebang to 
`#!/usr/bin/env python3`. Note that the executable python scripts in the plugins that come with pluma do not contain a shebang (e.g. see pluma/plugins/pythonconsole/pythonconsole/console.py).

**Comment by raveit65** [comment]
You're right, after adding the executable bit by hand in spec file of rpm i ran into this warning.
```
 /usr/lib/rpm/redhat/brp-mangle-shebangs
*** ERROR: ambiguous python shebang in /usr/lib64/pluma/plugins/synctex/atril_dbus.py: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
error: Bad exit status from /var/tmp/rpm-tmp.kX79sq (%install)
```
So, we need only to fix the shebang.
I will test if this make fedora-review tool silent.

**Comment by raveit65** [comment]
Nope, both lines are needed to fix the rpmlint warning.
```
sed -i 's|#!\/usr\/bin/\python|#!\/usr\/bin\/python3|g' plugins/synctex/synctex/atril_dbus.py

and after in install section of the rpm

chmod +x %{buildroot}/%{_libdir}/pluma/plugins/synctex/atril_dbus.py
```

**Comment by raveit65** [comment]
A little test:
```
[rave@mother ~]$ echo '#!/usr/bin/python3' > test.py 
[rave@mother ~]$ cat test.py 
#!/usr/bin/python3
[rave@mother ~]$ ls -la test.py 
-rw-rw-r-- 1 rave rave 19 15. Aug 13:11 test.py
[rave@mother ~]$ chmod +x test.py 
[rave@mother ~]$ ls -la test.py 
-rwxrwxr-x 1 rave rave 19 15. Aug 13:11 test.py
[rave@mother ~]$ 
```

**Comment by raveit65** [comment]
@mbkma 
In rhbz rewiew there is a open question about the shebang, see https://bugzilla.redhat.com/show_bug.cgi?id=1991208#c3
```
 Should atril_dbus.py really have a shebang at all?
  IOW instead of fixing the shebang, should it just be removed?
.
.
.
.
[?]: Final provides and requires are sane (see attachments).
     QUESTION: should atril_dbus.py really have a shebang at all?
     This causes a Requires: /usr/bin/python3 which seems incorrect.
```

**Comment by mbkma** [comment]
Yes, as already mentioned no python script from the plugins that ship with pluma have a shebang and it runs fine without.

**Comment by raveit65** [comment]
fixed with https://github.com/mate-desktop/pluma-plugins/commit/5b30940d7d0e4e290598c92b6bed648899937053
