### ISSUE TITLE
Not available in Ubuntu repos.

### ISSUE THREAD

**Issue by K0-RR** [mate-desktop/pluma-plugins#30]
I can install pluma by using `sudo apt install pluma` but `pluma-plugins` is not found.

#### Package version
1.24.2

#### Linux Distribution
Ubuntu Cinnamon

#### Link to bugreport of your Distribution (requirement)
what?

**Comment by mbkma** [comment]
It only works with pluma >= 1.26 anyway, so you will have to wait until 21.10 or 22.04 or build from source.
