### ISSUE TITLE
sourcecodebrowser comes with incomplete license text

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/pluma-plugins#34]
#### Expected behaviour

sourcecodebrowser using a proper (well-known) FOSS license...

#### Actual behaviour

Most files in the sourcecodebrowser plugin are attributed by an incomplete Free Software license:

```
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

This text sounds like the second half of the BSD license variants. Please amend this.

#### Steps to reproduce the behaviour

View these files:

sourcecodebrowser/sourcecodebrowser/ctags.py
sourcecodebrowser/sourcecodebrowser/__init__.py
sourcecodebrowser/sourcecodebrowser/sourcecodebrowser.py

#### MATE general version

1.26

#### Package version

1.26.0

#### Linux Distribution

Debian

#### Link to bugreport of your Distribution (requirement)

none

**Comment by rbuj** [comment]
https://github.com/MicahCarrick/gedit-source-code-browser is licensed under [3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause)
